### ISSUE TITLE
Update all vignettes with new bundle structure

### ISSUE THREAD

**Issue by jnkrupp** [HumanCellAtlas/data-consumer-vignettes#19]
## Definition of done
Change the vignettes so that they use the new bundle structure. This includes all vignettes except for _Install the HCA CLI_, _Log in to the DSS_, and _Stream FASTQs and Calculate k-mers with SPARK_.

Vignettes to update:
- [ ] Download any BAM file
- [ ] Download SmartSeq2 expression matrix as an input to scanpy
- [x] Find out how many liver (whatever) cells are available
- [x] Download all bundles for T-cells sequenced with 10x

Note that this issue is blocked until enough bundles of the new format with good metadata are indexed and available for querying/download.

**Comment by kozbo** [comment]
scrapping old tasks and reworking
