### ISSUE TITLE
Update vignettes to get analysis bundles from prod instead of integration

### ISSUE THREAD

**Issue by jnkrupp** [HumanCellAtlas/data-consumer-vignettes#20]
## Definition of done
Currently, there are two vignettes _Download SmartSeq2 expression matrix as an input to scanpy_ and _Compare QC metrics between one experiment and another_ which get analysis bundles from `integration`. 

These two vignettes should be updated get analysis bundles from `production` instead, which can be done by simply removing two cells from the notebook. One cell contains the code which changes `client.host` to `integration`, and the other cells contains an explanation of why.

Note that right now, there are no analysis bundles in `production`, so until there are, _this issue is blocked._

**Comment by kozbo** [comment]
Remove hard coding of the deployment.

**Comment by natanlao** [comment]
I can't find the _Compare QC metrics between one experiment and other_ notebook. There is reference to this notebook in the README, but even after comparing the repository history (f98e52b108522e5fe7dc7fc21dd648788f0de6e6 on August 15
and 0f5da66a5f45b7b76a4c29d5fdcc53d5aa455b97 October 30) I can't seem to locate it.
