### ISSUE TITLE
problems installing requirements

### ISSUE THREAD

**Issue by dosumis** [HumanCellAtlas/data-consumer-vignettes#22]
Stack trace:
```
/var/folders/bn/mw_hfq3n42lbt_vpd7h4rhfsfplj_1/T/H5close6uqqrouf.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    /var/folders/bn/mw_hfq3n42lbt_vpd7h4rhfsfplj_1/T/H5close6uqqrouf.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]
        H5close();
        ^
    2 warnings generated.
    ld: library not found for -lhdf5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    * Using Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
```

Do I need some kind of HDF5 installation outside of Python? (Apologies if this is a naive question).

**Comment by mckinsel** [comment]
Hey @dosumis, could you give a little more context?

**Comment by dosumis** [comment]
I'm try to pip install requirements.txt

It seems to choke on installing scanpy => the above error.  Note - I have h5py and loompy installed and working fine.

**Comment by dosumis** [comment]
I now have it working: For the record, I can get all dependencies to install with Python 3.6 - but at least one dependency fails in 3.5 & 3.7.

**Comment by joeklieg** [comment]
I have been working with Genevieve to create a web-based, dependency free version of the notebook. It is available here: https://nextjournal.com/chanzuckerberg/explore-an-hca-data-set-in-scanpy

If you would like the ability to edit and rerun the article yourself on the platform, you just need to
1) create an account on [Nextjournal]([nextjournal.com]) (you can use the private access code: `chanzuckerberg`)
2) ‘Remix’ the article (which gives you the article, the data, and the entire computational environment in a single click)
3) edit/run the article on the web

**Comment by natanlao** [comment]
We've seen `scanpy` and `loompy` giving some trouble during installation. This can generally be fixed by doing `sudo apt install libhdf5-dev` (or `brew install hdf5`). For propriety, we install the following for testing:

    $ sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran libhdf5-dev

**Comment by chmreid** [comment]
Re @joeklieg's attempt to create a web-based and dependency-free version of the notebook, we can also look into using https://mybinder.org/ (which can turn a repo into a Jupyter notebook, complete with installed conda environments).
