### ISSUE TITLE
update table of existing and planned vignettes

### ISSUE THREAD

**Issue by GenevieveHaliburton** [HumanCellAtlas/data-consumer-vignettes#24]
@mckinsel and @jnkrupp do you have any updates to the table of existing and planned vignettes? i'll update the table, just want to make sure i have the most up to date notes from y'all as well. thanks!

**Comment by kozbo** [comment]
We have established a CI/CD system for the vignettes. It sounds like vignettes are going to come from many different repos so we are thinking that the TOC for vignettes should be located in teh Portal here https://software.broadinstitute.org/wdl/documentation/topic?name=wdl-tutorials

We think that we should have a TOC of examples in the Portal, and that the user should be able to drill into the code from there.

We have created a number of other issues to track this approach.

**Comment by kozbo** [comment]
The basic table in the consumer-vignettes repo is up to date.
