### ISSUE TITLE
Need a vignette for Terra's Jupyter notebook system

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/data-consumer-vignettes#27]
We need someone to take point on creating (updating) a vignette for use in Terra’s Jupyter notebook system. The Notebook should be an updated version of Genevieve's notebook from our previous demo (“HCA Scanpy Demo”)... 

From our conversation on 20190425 none of the PLs/POs volunteered for this so this is now a stretch goal since we don't have a clear group to own this.

**Comment by joeklieg** [comment]
Worked with Genevieve last year to create this based on HCA Scanpy Demo:
https://nextjournal.com/genevieve/wip-explore-an-hca-data-set-in-scanpy

This is instantly executable/runnable for anyone with a Nextjournal account.

The computational environment it is based on is here:
https://nextjournal.com/chanzuckerberg/hca-environment

This could also work as a general CI/CD solution for vignettes.

**Comment by briandoconnor** [comment]
This work is done, I confirmed this morning that I was able to run the notebook in Terra and produce results similar enough to the run from Nov 2018.

I think the next step, though, is to write a tutorial on how I did this on the Portal site.

Can I get help on this from @NoopDog or someone from the Portal team?

**Comment by briandoconnor** [comment]
![temp.png](https://images.zenhubusercontent.com/5a70ce814b5806bc2bc4edde/96e09602-22ec-430b-a83a-5da140866dba)
