### ISSUE TITLE
Tutorial for “Download Any BAM File” vignette

### ISSUE THREAD

**Issue by theathorn** [HumanCellAtlas/data-consumer-vignettes#43]
There is a tutorial (on or pointed to from our “Guides” portal section) that a researcher can follow that will show them how to search and download data and perform some basic analysis. A great candidate for this is leveraging the “Download Any BAM File” vignette in a tutorial on our Data Portal site and including a very basic analysis example given some BAMs downloaded from HCA.

**Comment by theathorn** [comment]
@natanlao Can you add this ticket to the Epic https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/337.

I don't have permissions..

**Comment by natanlao** [comment]
@theathorn Done!

**Comment by theathorn** [comment]
We need content for a guide to this vignette added here: https://data.humancellatlas.org/guides/consumer-vignettes
