### ISSUE TITLE
Programmatically generate markdown ToC of vignettes

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/data-consumer-vignettes#48]
a la https://software.broadinstitute.org/wdl/documentation/topic?name=wdl-tutorials

**Comment by kozbo** [comment]
Vignettes will come from many different  repos, not just the data-consumer-vignettes repo. We like the TOC in that repo, but it will present a maintenance

**Comment by rexwangcc** [comment]
@kozbo 
> Vignettes will come from many different repos, not just the data-consumer-vignettes repo. How will we provide a way for users to browse them in a common location?

One approach we have been experimenting with is to render the notebooks and host them from a centralized place outside of Github repos. It will not only show the TOC but also the contents of the notebooks. See https://cromwell-tools.readthedocs.io/en/latest/Tutorials/Quickstart/api_quickstart.html as an example, updates to the vignettes that breaking the tests would be merged/deployed to the rendered page.

**Comment by chmreid** [comment]
The script to programmatically generate the table of contents was created and added, but never actually run, so the Readme links are all still broken. See #56.

**Comment by chmreid** [comment]
@jeffrey856 (And in meantime maybe fix Readme links by hand since it's linked to on front page of HCA and they've been broken for a while)

**Comment by chmreid** [comment]
Closed by #69
