### ISSUE TITLE
Links in Readme are broken

### ISSUE THREAD

**Issue by chmreid** [HumanCellAtlas/data-consumer-vignettes#56]
When I try to click the links to the notebooks that are listed on the Readme, they are all broken.

Note: relates to #48, programmatic generation of table of contents.

**Comment by ambrosejcarr** [comment]
+1, got here from the main landing page of the HCA. I was able to click through folder names and find the vignettes that way, but the `README` adds confusion. Given that the code itself is reasonably well organized, it could make sense to simply hide the TOC until programmatic generation can be carried out.

**Comment by chmreid** [comment]
@jeffrey856 I think issue #48 was closed prematurely

**Comment by chmreid** [comment]
Closed by #69
