### ISSUE TITLE
CI/CD failure notification pipeline

### ISSUE THREAD

**Issue by natanlao** [HumanCellAtlas/data-consumer-vignettes#66]
A large part of the value of CI/CD for this repo is the ability to periodically test documentation at rest to detect regressions in documentation accuracy. Travis is configured to build the repo weekly if the repo has not seen a normal build otherwise, but is not configured to notify anyone in the event of a failure. It should.

**Comment by amarjandu** [comment]
@natanlao  it looks like the pipeline is failing but not showing a failed status. https://travis-ci.com/HumanCellAtlas/data-consumer-vignettes/jobs/246815647

**Comment by natanlao** [comment]
@amarjandu Can you check your link? I don't see any failed builds in the [last month or so](https://travis-ci.com/HumanCellAtlas/data-consumer-vignettes/builds)...

**Comment by natanlao** [comment]
Ah, I see the issue - `treon` isn't failing the build. I'll look at this now.

**Comment by chmreid** [comment]
Please see #74 - that PR adds a cell to the top of one of the notebooks that raises an exception. I would expect this to break the CI/CD pipeilne, but the Travis build is still green.

**Comment by natanlao** [comment]
https://github.com/HumanCellAtlas/data-consumer-vignettes/pull/74#issuecomment-566191070
