### ISSUE TITLE
Update Matrix Service URL in HCA Scanpy Demo - May 2019

### ISSUE THREAD

**Issue by amarjandu** [HumanCellAtlas/data-consumer-vignettes#70]
URL is broken in the README.

**Comment by chmreid** [comment]
You talkin about the last URL in [this readme](https://github.com/HumanCellAtlas/data-consumer-vignettes/blob/master/Explore%20an%20HCA%20Data%20Set%20in%20Scanpy%20(May%202019)/README.md)?

Maybe turn it into a code block and state that it is just an example of what the link should look like.

**Comment by amarjandu** [comment]
https://s3.amazonaws.com/dcp-matrix-service-results-prod/3938cf5a-3159-4eb7-aef5-59589795c268.loom

**Comment by chmreid** [comment]
this will be closed by #72
