### ISSUE TITLE
Remediate High Netty vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/data-consumer-vignettes#80]
Snyk reports the following **High** severity vulnerability in HumanCellAtlas/data-consumer-vignettes. Please remediate by the end of Q1 Milestone 1.

### **Description**
io.netty:netty

### **Suggested Remediation**
Upgrade io.netty:netty to version 3.9.8.Final, 3.10.3.Final or higher.

### **Details**
io.netty:netty is a NIO client server framework which enables quick and easy development of network applications such as protocol servers and clients. Affected versions of this package are vulnerable to Information Disclosure. It does not validate cookie name and value characters, allowing attackers to potentially bypass the httpOnly flag on sensitive cookies.

**Comment by chmreid** [comment]
Can you clarify where you found netty being used in the consumer vignettes repo?

**Comment by chmreid** [comment]
https://github.com/HumanCellAtlas/data-consumer-vignettes/search?utf8=%E2%9C%93&q=netty&type= shows 0 results

**Comment by chmreid** [comment]
PR #83 should remediate this vulnerability, please re-open if not
