### ISSUE TITLE
Remediate High Zookeeper vulnerability

### ISSUE THREAD

**Issue by Lilalamar** [HumanCellAtlas/data-consumer-vignettes#81]
Snyk reports the following **High** severity vulnerability in HumanCellAtlas/data-consumer-vignettes. Please remediate by the end of Q1 Milestone 1.

### **Description**
org.apache.zookeeper:zookeeper

### **Suggested Remediation**
Upgrade org.apache.zookeeper:zookeeper to version 3.4.10, 3.5.4-beta or higher.

### **Details**
org.apache.zookeeper:zookeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services. Affected versions of this package are vulnerable to Authentication Bypass. No authentication/authorization is enforced when a server attempts to join a quorum, as a result an arbitrary end point could join the cluster and begin propagating counterfeit changes to the leader.

**Comment by chmreid** [comment]
Same question as #80 - where is zookeeper being used in this repo? https://github.com/HumanCellAtlas/data-consumer-vignettes/search?q=zookeeper&unscoped_q=zookeeper

**Comment by chmreid** [comment]
PR #83 should remediate this vulnerability, please re-open if not
